FileVersion = 1
Projects = {block-heroes = {Path = "."}, Ariyana_beef = {Path = "../ariyana/Beef"}, CurlBeef = {Path = "../ariyana/Beef/deps/CurlBeef"}}
ExtraPlatforms = ["Linux64", "armv7-none-linux-android21"]

[Workspace]
StartupProject = "block-heroes"

[[Configs.ServerDebug.Win64.DistinctOptions]]
Filter = ""
