FileVersion = 1
Dependencies = {corlib = "*", Ariyana_beef = "*", imgui-beef = "*"}

[Project]
Name = "block-heroes"
StartupObject = "bh.Program"
DefaultNamespace = "bh"

[Configs.Debug.armv7-none-linux-android21]
BuildKind = "StaticLib"
TargetName = "lib$(ProjectName)"
RelocType = "PIC"

[Configs.Debug.Win64]
DebugCommandArguments = "-p 2323"

[Configs.Release.armv7-none-linux-android21]
BuildKind = "StaticLib"
TargetName = "lib$(ProjectName)"
RelocType = "PIC"

[Configs.Paranoid.armv7-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.Test.armv7-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.ServerDebug.Win32]
BeefLibType = "Static"

[Configs.ServerDebug.Win64]
BeefLibType = "Static"
PreprocessorMacros = ["DEBUG", "ARI_SERVER"]

[Configs.ServerDebug.armv7-none-linux-android21]
TargetName = "lib$(ProjectName)"
BeefLibType = "Static"
RelocType = "PIC"

[Configs.ServerDebug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lcari -lcurl -lssl -lcrypto -lz -lpthread"
BeefLibType = "Static"
LibPaths = ["-L$(ProjectDir)/../ariyana/Beef/dist/linux64/ServerDebug", "-L$(ProjectDir)/../ariyana/Beef/deps/CurlBeef/dist/linux64"]
PreprocessorMacros = ["DEBUG", "ARI_SERVER"]
